# Generated by Django 5.2.5 on 2025-10-15 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "engage_uuid",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Engage uuid",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_is_verified", models.BooleanField(default=False)),
                ("suspended", models.BooleanField(default=False)),
                ("can_withdraw", models.BooleanField(default=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WEB", "WEB"),
                            ("APP/POS", "APP/POS"),
                            ("MOBILE", "MOBILE"),
                        ],
                        default="WEB",
                        max_length=200,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "USER",
                "verbose_name_plural": "USERS",
            },
        ),
        migrations.CreateModel(
            name="TelcosPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NETWORK_PROVIDER", "NETWORK_PROVIDER"),
                            ("MTN", "MTN"),
                            ("9MOBILE", "9MOBILE"),
                            ("GLO", "GLO"),
                            ("AIRTEL", "AIRTEL"),
                        ],
                        default="NETWORK_PROVIDER",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GENDER", "GENDER"),
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                        ],
                        default="GENDER",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, default=0, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "usage_naira",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("phone_type", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("lga", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TELCO PHONE NUMBER",
                "verbose_name_plural": "TELCO PHONE NUMBERS",
                "unique_together": {("phone_number", "network")},
            },
        ),
        migrations.CreateModel(
            name="UserProfileOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(editable=False, max_length=200)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "otp_type",
                    models.CharField(
                        choices=[("EMAIL_VERIFICATION", "EMAIL_VERIFICATION")],
                        default="EMAIL_VERIFICATION",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "USER PROFILE OTP",
                "verbose_name_plural": "USER PROFILE OTP",
            },
        ),
    ]
