# Generated by Django 5.2.5 on 2025-10-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text='{"emails": ["email1@example.com", "email2@example.com"],"phones": ["123-456-7890", "987-654-3210"]}'
                    ),
                ),
                (
                    "withdrawal",
                    models.JSONField(
                        blank=True,
                        help_text='{"emails": ["email1@example.com", "email2@example.com"],"phones": ["123-456-7890", "987-654-3210"]}',
                        null=True,
                    ),
                ),
                (
                    "instant_cashout_game",
                    models.JSONField(
                        blank=True,
                        help_text='{"emails": ["email1@example.com", "email2@example.com"],"phones": ["123-456-7890", "987-654-3210"]}',
                        null=True,
                    ),
                ),
                (
                    "salary_for_life_game",
                    models.JSONField(
                        blank=True,
                        help_text='{"emails": ["email1@example.com", "email2@example.com"],"phones": ["123-456-7890", "987-654-3210"]}',
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BLACK LISTED",
                "verbose_name_plural": "BLACK LISTED",
            },
        ),
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=200)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "otp_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "REGISTRATION"),
                            ("PHONE_NUMBER_OTP", "PHONE_NUMBER_OTP"),
                            ("PHONE_NUMBER_ACTIVATION", "PHONE_NUMBER_ACTIVATION"),
                        ],
                        default="REGISTRATION",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ussd_code_extension",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP TABLE",
                "verbose_name_plural": "OTP TABLES",
            },
        ),
        migrations.CreateModel(
            name="ResetPasswordToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="When was this token generated"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Key"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="The IP address of this session",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="HTTP User Agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The User which is associated to this password reset token",
                    ),
                ),
            ],
            options={
                "verbose_name": "PASSWORD RESET TOKEN",
                "verbose_name_plural": "PASSWORD RESET TOKENS",
            },
        ),
    ]
