# Generated by Django 5.2.5 on 2025-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LotteryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_num",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150, null=True)),
                ("bank_code", models.CharField(blank=True, max_length=150, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "loandisk_player_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("on_loandisk", models.BooleanField(default=False)),
                ("ministry", models.CharField(blank=True, max_length=300, null=True)),
                ("auth_code", models.CharField(blank=True, max_length=100, null=True)),
                ("bvn_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=200,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("USSD", "USSD"),
                            ("WEB", "WEB"),
                            ("USSD/WEB", "USSD/WEB"),
                            ("WEB/USSD", "WEB/USSD"),
                            ("MOBILE", "MOBILE"),
                            ("POS", "POS"),
                        ],
                        default="USSD",
                        max_length=200,
                    ),
                ),
                ("pin", models.CharField(blank=True, max_length=125, null=True)),
                ("has_pin", models.BooleanField(default=False)),
                ("has_web_virtual_account", models.BooleanField(default=False)),
                ("has_sudo_phone_number", models.BooleanField(default=False)),
                ("has_sudo_email", models.BooleanField(default=False)),
                ("suspended", models.BooleanField(default=False)),
                ("avatar", models.URLField(blank=True, max_length=2300, null=True)),
                ("debt_amount", models.FloatField(default=0.0)),
                ("recovered_debt", models.FloatField(default=0.0)),
                ("from_telco", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, editable=False, max_length=250, null=True
                    ),
                ),
                ("email_is_verified", models.BooleanField(default=False)),
                (
                    "preverified_email",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "network_provider",
                    models.CharField(
                        blank=True,
                        choices=[("MTN", "MTN"), ("GLO", "GLO")],
                        max_length=125,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
