# Generated by Django 5.2.5 on 2025-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotterymodel",
            name="phone",
            field=models.CharField(default="09023621202", max_length=300),
            preserve_default=False,
        ),
    ]
