# Generated by Django 5.2.5 on 2025-10-21 12:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_lotterymodel_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryGlobalJackPot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold", models.FloatField(default=0.0)),
                ("contributed_amount", models.FloatField(default=0.0)),
                (
                    "lottery_type",
                    models.CharField(
                        choices=[
                            ("SALARY_FOR_LIFE", "SALARY_FOR_LIFE"),
                            ("INSTANT_CASHOUT", "INSTANT_CASHOUT"),
                        ],
                        default="SALARY_FOR_LIFE",
                        max_length=250,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_drawn", models.BooleanField(default=False)),
                (
                    "jackpot_id",
                    models.CharField(default=uuid.uuid4, max_length=250, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SALARY FOR LIFE JACKPOT",
                "verbose_name_plural": "SALARY FOR LIFE JACKPOT",
            },
        ),
        migrations.CreateModel(
            name="LotteryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_uuid",
                    models.CharField(
                        default=main.models.generate_batch_uuid_func, max_length=150
                    ),
                ),
                (
                    "total_players_in_pool",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_unique_players_in_pool",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_unique_paid_playyers_in_pool",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_accumulated_unpaid", models.FloatField(blank=True, null=True)),
                ("total_accumulated_paid", models.FloatField(blank=True, null=True)),
                ("total_accumulated_all", models.FloatField(blank=True, null=True)),
                ("total_jackpot_amount_10", models.FloatField(blank=True, null=True)),
                ("total_jackpot_amount_50", models.FloatField(blank=True, null=True)),
                ("total_jackpot_amount_250", models.FloatField(blank=True, null=True)),
                ("total_jackpot_amount_500", models.FloatField(blank=True, null=True)),
                ("total_jackpot_amount_1000", models.FloatField(blank=True, null=True)),
                ("total_amount_won", models.FloatField(blank=True, null=True)),
                ("RTO", models.FloatField(default=30)),
                ("RTP", models.FloatField(blank=True, null=True)),
                ("total_revenue", models.FloatField(blank=True, null=True)),
                ("super_winers", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_pos_active", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("draw_date", models.DateTimeField(blank=True, null=True)),
                ("batch_start", models.DateTimeField(blank=True, null=True)),
                ("batch_end", models.DateTimeField(blank=True, null=True)),
                (
                    "lottery_type",
                    models.CharField(
                        choices=[
                            ("SALARY_FOR_LIFE", "SALARY_FOR_LIFE"),
                            ("INSTANT_CASHOUT", "INSTANT_CASHOUT"),
                            ("WYSE_CASH", "WYSE_CASH"),
                            ("WHYSE_LOAN", "WHYSE_LOAN"),
                            ("QUIKA", "QUIKA"),
                            ("BANKER", "BANKER"),
                        ],
                        default="WHYSE_LOAN",
                        max_length=100,
                    ),
                ),
                (
                    "lottery_winner_ticket",
                    models.TextField(
                        blank=True,
                        help_text="Serialization of the winner ticket/selection of numbers",
                        null=True,
                    ),
                ),
                (
                    "lottery_winner_ticket_number",
                    models.TextField(
                        blank=True, help_text="The winning ticket number", null=True
                    ),
                ),
                (
                    "instant_cashout_player_threshold",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("is_pos_batch", models.BooleanField(default=False)),
                (
                    "list_of_ticket_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("manually_filtered_winnings", models.BooleanField(default=False)),
                ("pending_telco_draw", models.BooleanField(default=False)),
                (
                    "global_jackpot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.lotteryglobaljackpot",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOTTERY BATCH",
                "verbose_name_plural": "LOTTERY BATCHES",
            },
        ),
        migrations.CreateModel(
            name="LottoTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=300)),
                ("stake_amount", models.FloatField(default=0.0)),
                ("potential_winning", models.FloatField(default=0.0)),
                ("expected_amount", models.FloatField(default=0.0)),
                ("amount_paid", models.FloatField(db_index=True, default=0.0)),
                ("illusion", models.FloatField(default=0.0)),
                ("rto", models.FloatField(default=0.0)),
                ("rtp", models.FloatField(default=0.0)),
                ("rtp_per", models.FloatField(default=0.0)),
                ("effective_rtp", models.FloatField(default=0.0)),
                ("commission_per", models.FloatField(default=0.0)),
                ("commission_value", models.FloatField(default=0.0)),
                ("salary_for_life_jackpot_per", models.FloatField(default=0.0)),
                ("salary_for_life_jackpot_amount", models.FloatField(default=0.0)),
                ("win_commission_per", models.FloatField(default=0.0)),
                ("win_commission_value", models.FloatField(default=0.0)),
                ("ussd_telco_commission", models.FloatField(default=0.0)),
                ("ussd_telco_commission_value", models.FloatField(default=0.0)),
                ("ussd_telco_aggregator_commission", models.FloatField(default=0.0)),
                (
                    "ussd_telco_aggregator_commission_value",
                    models.FloatField(default=0.0),
                ),
                ("paid", models.BooleanField(db_index=True, default=False)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number_of_ticket", models.IntegerField(db_index=True, default=0)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("USSD", "USSD"),
                            ("USSD_WEB", "USSD_WEB"),
                            ("WEB", "WEB"),
                            ("MOBILE", "MOBILE"),
                            ("POS_AGENT", "POS_AGENT"),
                            ("SYSTEM_BONUS", "SYSTEM_BONUS"),
                        ],
                        db_index=True,
                        default="POS_AGENT",
                        max_length=150,
                    ),
                ),
                (
                    "game_play_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                (
                    "unique_game_play_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "awoof_game_play_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "lottery_type",
                    models.CharField(
                        choices=[
                            ("SALARY_FOR_LIFE", "SALARY_FOR_LIFE"),
                            ("INSTANT_CASHOUT", "INSTANT_CASHOUT"),
                            ("QUIKA", "QUIKA"),
                            ("VIRTUAL_SOCCER", "VIRTUAL_SOCCER"),
                            ("BANKER", "BANKER"),
                        ],
                        db_index=True,
                        default="SALARY_FOR_LIFE",
                        max_length=150,
                    ),
                ),
                (
                    "lottery_source",
                    models.CharField(
                        choices=[("NORMAL", "NORMAL"), ("BONUS", "BONUS")],
                        db_index=True,
                        default="NORMAL",
                        max_length=150,
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("AWOOF", "AWOOF"), ("NORMAL", "NORMAL")],
                        db_index=True,
                        default="NORMAL",
                        max_length=150,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("AWOOF", "AWOOF"), ("INSURANCE", "INSURANCE")],
                        db_index=True,
                        default="AWOOF",
                        help_text="the type of service played, Awoof or Insurance",
                        max_length=150,
                    ),
                ),
                ("has_interest", models.BooleanField(default=True)),
                (
                    "ticket",
                    models.CharField(
                        help_text="Serialization of the ticket/selection of numbers made by the player",
                        max_length=200,
                    ),
                ),
                (
                    "system_generated_num",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "win_combo",
                    models.CharField(
                        blank=True,
                        help_text="Actual complete winning number for batch",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_agent", models.BooleanField(default=False)),
                ("s4l_drawn", models.BooleanField(default=False)),
                ("instant_cashout_drawn", models.BooleanField(default=False)),
                ("pos_instant_cashout_drawn", models.BooleanField(default=False)),
                ("icash_counted", models.BooleanField(default=False)),
                ("icash_2_counted", models.BooleanField(default=False)),
                ("icash_local_counted", models.BooleanField(default=False)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "game_id_treated",
                    models.BooleanField(
                        default=False,
                        help_text="This tracks if or not a game id has been treated or not, because instant cash treats individual tickets seperately, but the paid amounts are not lumped, but have to be infered by a multiplication by the game ID.",
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        help_text="Pin use for cashout if the lottery is played from POS_AGENT and the player didn't provide his phone number. This's not the same as the pin used for retail ticket",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "identity_id",
                    models.CharField(
                        blank=True,
                        help_text="This is basically created for transactional purpose",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("played_via_telco_channel", models.BooleanField(default=False)),
                (
                    "telco_channel",
                    models.CharField(
                        choices=[
                            ("BROADBASE", "BROADBASE"),
                            ("YELLOW_DOT_AFRICA", "YELLOW_DOT_AFRICA"),
                        ],
                        default="BROADBASE",
                        help_text="This is the channel through which the ticket was played, either via telco or not",
                        max_length=150,
                    ),
                ),
                ("is_new_quika_game", models.BooleanField(default=False)),
                (
                    "telco_network",
                    models.CharField(
                        blank=True,
                        choices=[("MTN", "MTN"), ("GLO", "GLO")],
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "drawn_for",
                    models.CharField(
                        choices=[("GLOBAL", "GLOBAL"), ("LOCAL", "LOCAL")],
                        default="GLOBAL",
                        max_length=25,
                    ),
                ),
                (
                    "seeder_status",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "COMPLETE"),
                            ("PROCESSING", "PROCESSING"),
                            ("PENDING", "PENDING"),
                        ],
                        default="PENDING",
                        help_text="Current status of the seeder for this ticket.",
                        max_length=100,
                    ),
                ),
                ("content_delivery_sms_sent", models.BooleanField(default=False)),
                ("product_id", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.lotterybatch",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "SALARY FOR LIFE & INSTANT CASHOUT TICKET",
                "verbose_name_plural": "SALARY FOR LIFE & INSTANT CASHOUT TICKETS",
                "indexes": [
                    models.Index(
                        fields=["phone", "paid", "channel"],
                        name="main_lottot_phone_5d2149_idx",
                    ),
                    models.Index(
                        fields=["game_play_id"], name="main_lottot_game_pl_4bbb67_idx"
                    ),
                    models.Index(fields=["paid"], name="main_lottot_paid_b458dc_idx"),
                    models.Index(
                        fields=["channel"], name="main_lottot_channel_4aeba2_idx"
                    ),
                    models.Index(fields=["phone"], name="main_lottot_phone_c9044b_idx"),
                    models.Index(
                        fields=["lottery_type"], name="main_lottot_lottery_26b8a2_idx"
                    ),
                    models.Index(
                        fields=["seeder_status"], name="main_lottot_seeder__cf5451_idx"
                    ),
                    models.Index(
                        django.db.models.functions.datetime.TruncDate("date"),
                        models.F("date"),
                        name="date_date_idx",
                    ),
                ],
            },
        ),
    ]
