# Generated by Django 5.2.5 on 2025-11-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_constantvariable4_alter_lotteryglobaljackpot_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryWinnersTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_batch_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("phone_number", models.CharField(max_length=150)),
                ("playyer_id", models.PositiveIntegerField(blank=True, null=True)),
                ("unnique_id", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "game_play_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "game_id",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("ticket", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "win_type",
                    models.CharField(
                        choices=[
                            ("JACKPOT_WINNER", "JACKPOT_WINNER"),
                            ("ORDINARY_WINNER", "ORDINARY_WINNER"),
                            ("SUPER_WINNER", "SUPER_WINNER"),
                            ("CROWN_JUMBO_WINNER", "CROWN_JUMBO_WINNER"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "pool",
                    models.CharField(
                        choices=[
                            ("TEN_THOUSAND", "TEN_THOUSAND"),
                            ("FIFTY_THOUSAND", "FIFTY_THOUSAND"),
                            ("ONE_HUNDRED_THOUSAND", "ONE_HUNDRED_THOUSAND"),
                            ("TWO_HUNDRED_THOUSAND", "TWO_HUNDRED_THOUSAND"),
                            ("TWO_FIFTY_THOUSAND", "TWO_FIFTY_THOUSAND"),
                            ("FIVE_HUNDRED_THOUSAND", "FIVE_HUNDRED_THOUSAND"),
                            ("ONE_MILLION", "ONE_MILLION"),
                            ("TWO_MILLION", "TWO_MILLION"),
                        ],
                        max_length=150,
                    ),
                ),
                ("share", models.CharField(blank=True, max_length=150, null=True)),
                ("stake_amount", models.FloatField(blank=True, null=True)),
                ("earning", models.FloatField(default=0.0)),
                ("total_jackpot_amount", models.FloatField(default=0.0)),
                ("date_won", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "lottery_source_tag",
                    models.CharField(
                        choices=[
                            ("USSD", "USSD"),
                            ("USSD_WEB", "USSD_WEB"),
                            ("WEB", "WEB"),
                            ("MOBILE", "MOBILE"),
                            ("POS_AGENT", "POS_AGENT"),
                            ("BONUS", "BONUS"),
                        ],
                        default="USSD",
                        max_length=150,
                    ),
                ),
                ("played_via_telco_channel", models.BooleanField(default=False)),
                ("won_jackpot", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_lottery_winners",
                        to="main.lotterybatch",
                    ),
                ),
                (
                    "lottery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.lotterymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "WYSE CASH WINNERS TABLE",
                "verbose_name_plural": "WYSE CASH WINNERS TABLES",
            },
        ),
        migrations.CreateModel(
            name="DisbursementTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_phone_num",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("payout_amount", models.FloatField()),
                (
                    "payout_account_num",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "payout_account_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "payout_bank_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "payout_bank_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("disbursement_payload", models.TextField(blank=True, null=True)),
                ("is_disbursed", models.BooleanField(default=False)),
                ("payyment_verified", models.BooleanField(default=False)),
                ("is_demmo_player", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "stattus",
                    models.CharField(
                        choices=[
                            ("NOT_INITIATED", "NOT_INITIATED"),
                            ("INITIATED", "INITIATED"),
                            ("PROCESSING", "PROCESSING"),
                            ("DISBURSED", "DISBURSED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="NOT_INITIATED",
                        max_length=100,
                    ),
                ),
                ("collect_bvn", models.BooleanField(default=False)),
                (
                    "lottery_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_disbursable_payouts",
                        to="main.lotterybatch",
                    ),
                ),
                (
                    "lotery_winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lottery_disbursement",
                        to="main.lotterywinnerstable",
                    ),
                ),
            ],
            options={
                "verbose_name": "DISBURSEMENT TABLE",
                "verbose_name_plural": "DISBURSEMENT TABLES",
            },
        ),
    ]
